### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by namdeptrai2003** [Atomic-OS/platform_manifest#2]
FAILED: /home/abod/Atomic/out/target/product/kylepro/obj/ETC/sepolicy_intermediates/sepolicy 
/bin/bash -c "(/home/abod/Atomic/out/host/linux-x86/bin/checkpolicy -M -c 30 -o /home/abod/Atomic/out/target/product/kylepro/obj/ETC/sepolicy_intermediates/sepolicy.tmp /home/abod/Atomic/out/target/product/kylepro/obj/ETC/sepolicy_intermediates/policy.conf ) && (/home/abod/Atomic/out/host/linux-x86/bin/checkpolicy -M -c 30 -o /home/abod/Atomic/out/target/product/kylepro/obj/ETC/sepolicy_intermediates//sepolicy.dontaudit /home/abod/Atomic/out/target/product/kylepro/obj/ETC/sepolicy_intermediates/policy.conf.dontaudit ) && (/home/abod/Atomic/out/host/linux-x86/bin/sepolicy-analyze /home/abod/Atomic/out/target/product/kylepro/obj/ETC/sepolicy_intermediates/sepolicy.tmp permissive > /home/abod/Atomic/out/target/product/kylepro/obj/ETC/sepolicy_intermediates/sepolicy.permissivedomains ) && (if [ \"userdebug\" = \"user\" -a -s /home/abod/Atomic/out/target/product/kylepro/obj/ETC/sepolicy_intermediates/sepolicy.permissivedomains ]; then 		echo \"==========\" 1>&2; 	echo \"ERROR: permissive domains not allowed in user builds\" 1>&2; 		echo \"List of invalid domains:\" 1>&2; 		cat /home/abod/Atomic/out/target/product/kylepro/obj/ETC/sepolicy_intermediates/sepolicy.permissivedomains 1>&2; 		exit 1; 		fi ) && (mv /home/abod/Atomic/out/target/product/kylepro/obj/ETC/sepolicy_intermediates/sepolicy.tmp /home/abod/Atomic/out/target/product/kylepro/obj/ETC/sepolicy_intermediates/sepolicy )"
device/samsung/kylepro/sepolicy/sysinit.te:2:ERROR 'unknown type sysinit' at token ';' on line 21510:
allow sysinit system_file:lnk_file { getattr };
#line 1 "device/samsung/kylepro/sepolicy/sysinit.te"
checkpolicy:  error(s) encountered while parsing configuration

**Comment by TheDarkStrix** [comment]
This is a device issue :: device/samsung/kylepro/sepolicy/sysinit.te:2:ERROR 'unknown type sysinit' at token ';' on line 21510:
allow sysinit system_file:lnk_file { getattr };

**Comment by namdeptrai2003** [comment]
Ok thanks

**Comment by namdeptrai2003** [comment]
I deleted that line but still failed

**Comment by TheDarkStrix** [comment]
Do u have a commit , where i can see the line you deleted ?

**Comment by namdeptrai2003** [comment]
I deleted in my pc....

**Comment by namdeptrai2003** [comment]
Because i'm build it now

**Comment by namdeptrai2003** [comment]
![sfhs](https://user-images.githubusercontent.com/24204127/29495679-207f0f76-85ee-11e7-999d-36b2db2b40ec.PNG)

**Comment by namdeptrai2003** [comment]
permissive domains not allowed in user builds"

**Comment by namdeptrai2003** [comment]
Anyway to fix this

**Comment by TheDarkStrix** [comment]
In the Screenshot u post , there is no error

**Comment by namdeptrai2003** [comment]
35% 11136/31196] build /home/abod/Atomic/out/target/product/kylepro/obj/ETC/sepolicy_intermediates/sepolicy
FAILED: /home/abod/Atomic/out/target/product/kylepro/obj/ETC/sepolicy_intermediates/sepolicy 
/bin/bash -c "(/home/abod/Atomic/out/host/linux-x86/bin/checkpolicy -M -c 30 -o /home/abod/Atomic/out/target/product/kylepro/obj/ETC/sepolicy_intermediates/sepolicy.tmp /home/abod/Atomic/out/target/product/kylepro/obj/ETC/sepolicy_intermediates/policy.conf ) && (/home/abod/Atomic/out/host/linux-x86/bin/checkpolicy -M -c 30 -o /home/abod/Atomic/out/target/product/kylepro/obj/ETC/sepolicy_intermediates//sepolicy.dontaudit /home/abod/Atomic/out/target/product/kylepro/obj/ETC/sepolicy_intermediates/policy.conf.dontaudit ) && (/home/abod/Atomic/out/host/linux-x86/bin/sepolicy-analyze /home/abod/Atomic/out/target/product/kylepro/obj/ETC/sepolicy_intermediates/sepolicy.tmp permissive > /home/abod/Atomic/out/target/product/kylepro/obj/ETC/sepolicy_intermediates/sepolicy.permissivedomains ) && (if [ \"userdebug\" = \"user\" -a -s /home/abod/Atomic/out/target/product/kylepro/obj/ETC/sepolicy_intermediates/sepolicy.permissivedomains ]; then 		echo \"==========\" 1>&2; 	echo \"ERROR: permissive domains not allowed in user builds\" 1>&2; 		echo \"List of invalid domains:\" 1>&2; 		cat /home/abod/Atomic/out/target/product/kylepro/obj/ETC/sepolicy_intermediates/sepolicy.permissivedomains 1>&2; 		exit 1; 		fi ) && (mv /home/abod/Atomic/out/target/product/kylepro/obj/ETC/sepolicy_intermediates/sepolicy.tmp /home/abod/Atomic/out/target/product/kylepro/obj/ETC/sepolicy_intermediates/sepolicy )"
vendor/aos/sepolicy/vold.te:13:ERROR 'unknown type persist_file' at token ';' on line 21781:

allow vold persist_file:dir { getattr read open ioctl };
checkpolicy:  error(s) encountered while parsing configuration

**Comment by namdeptrai2003** [comment]
New failed falling from sky

**Comment by namdeptrai2003** [comment]
![s](https://user-images.githubusercontent.com/24204127/29495742-41a32bd2-85ef-11e7-9317-5c6af9a3815c.PNG)

**Comment by namdeptrai2003** [comment]
After delete the files

**Comment by namdeptrai2003** [comment]
permissive domains not allowed in user builds

**Comment by namdeptrai2003** [comment]
That mean i'm cant build it because i'm not this rom maintainer ?
